spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&options=reference%3Dprqowmqmkeqhpkkxqfdz&prepareThreshold=0"
    username: postgres.prqowmqmkeqhpkkxqfdz
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Email configuration (Gmail SMTP)
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:hoangduy20407@gmail.com}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls-fallback: false
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080

# VNPAY configuration
vnpay:
  tmn-code: 2MC6Z5TR
  secret-key: ${VNPAY_SECRET_KEY}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: https://frugality-creation-concrete.ngrok-free.dev/api/v1/payment/vnpay-callback
  api-url: https://api.sandbox.vnpayment.vn

# JWT configuration
app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:5173}
  cache:
    wallet-balance-ttl-seconds: 300
    wallet-history-ttl-seconds: 120
  jwt:
    expiration-ms: 480000000000
    refresh-expiration-ms: 604800000
    secret: ${APP_JWT_SECRET}

auth:
  login-attempt:
    max-attempts: 5
    window-minutes: 10
    block-duration-minutes: 10

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:diq6fckpj}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER:mock/professional-certificates}
